export enum ENUM_MOVIMIENTOS {
  DEPOSTIO = 'DEP',
  RETIRO = 'RET',
  NOTA_CREDITO = 'NCR',
  NOTA_DEBITO = 'NDB',
}

export enum ENUM_MOVIMIENTOS_DESCRIPCION {
  DEPOSTIO = 'DEPÓSITO',
  RETIRO = 'RETIRO',
  NOTA_CREDITO = 'NOTA DE CRÉDITO',
  NOTA_DEBITO = 'NOTA DE DÉBITO',
}

export enum ENUM_IDENTICADOR_MOVIMIENTOS {
  INGRESO = '+',
  EGRESO = '-',
}
