export class EliminarRetiroMovimientoDto {
  readonly _id: string;
  readonly observacion: string;
  readonly id: string; // * dato del token de autorización...
  readonly usuario: string; // * dato del token de autorización...
  readonly nombres: string; // * dato del token de autorización...
}
